Feature/typescript
jhildenbiddle/mergician pull request #2
Opened 2022-08-06 09:53 UTC by dror-weiss

Add typescript support.

This will enable the following from a package using Typescript for development:
```ts
import mergician from 'mergician';
```

Closes: #1

2022-08-06 17:42 UTC, jhildenbiddle commented
Brilliant. Thank you, @dror-weiss. I will get to this sometime next week.

2022-08-23 11:09 UTC, Arraying commented
> Brilliant. Thank you, @dror-weiss. I will get to this sometime next week.

Any updates on this?

2022-08-26 17:54 UTC, jhildenbiddle commented
My apologies for the delay @dror-weiss. I've been away but will return on Sunday. I will merge this as soon as I get back.

Thanks again!

2022-09-13 14:31 UTC, jhildenbiddle requested changes
Finally getting around to this. I appreciate your patience, @dror-weiss. 

I do have a few questions, most of which I'm sure are due to my lack of familiarity with TypeScript. The two assumptions I'm have about these TypeScript definitions is that they will...

1. Catch type mismatch issues in IDEs (VS Code) and during compilation (`tsc -p`)
2. Display relevant information in IDEs while editing

The issue I'm having is that neither of the two benefits above are working. Details below.

2022-09-13 14:31 UTC, jhildenbiddle commented on types/mergician.d.ts
> +	function mergician<T extends ObjectLiteral>(options: MergicianOptions): (...objects: ObjectLiteral[]) => T;
FWIW, having the function overloads available that demonstrate different ways of calling `mergician` is great. I wasn't aware of this functionality. I'm going to update the JSDoc comments to match after this PR is merged.

2022-09-13 14:31 UTC, jhildenbiddle commented on package.json
> +	"test:types": "tsc -p tests/types",
Am I correct that the purpose of this test to verify that `mergician.d.ts` will not break the TypeScript compiler? If so, the code contained within `tests/types/index.ts` is irrelevant and could be replaced with something as simple as the the following, yes?

```js
import mergician from 'mergician';

mergician({});
```

2022-09-14 20:19 UTC, jhildenbiddle commented on types/mergician.d.ts
> +		appendArrays?: boolean;
If option names and types are defined by the `MergicianOptions` interface, I would expect the following to throw an error:

```js
const customMergeFn = mergician({
  appendArrays: 1
});
```

Unfortunately, no error is displayed in VS Code or when during compilation.

2022-09-14 20:42 UTC, jhildenbiddle commented
@dror-weiss -- Ping!
@Arraying -- Feel free to jump in.

2023-06-06 14:19 UTC, threeal commented
any progress on this? @jhildenbiddle

2024-01-18 21:52 UTC, jhildenbiddle commented
@dror-weiss, @threeal --

Type definitions are now available in v2. Closing this PR.

2024-01-18 21:52 UTC, closed without merging